# Generated by Django 3.2.2 on 2021-05-08 07:55

import advisorapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisorapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisor_name', models.CharField(max_length=255)),
                ('advisor_photo', models.ImageField(max_length=1000, upload_to=advisorapp.models.image_upload)),
            ],
        ),
    ]
