# Generated by Django 3.2.2 on 2021-05-08 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advisorapp', '0002_advisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookaCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_time', models.DateTimeField(auto_now=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisorapp.advisor')),
            ],
        ),
    ]
