# Generated by Django 3.2.2 on 2021-05-08 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisorapp', '0003_bookacall'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookaCall',
            new_name='BookedCall',
        ),
    ]
