# Generated by Django 3.2.2 on 2021-05-08 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advisorapp', '0004_rename_bookacall_bookedcall'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedcall',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='advisorapp.user'),
            preserve_default=False,
        ),
    ]
