# Generated by Django 3.2.2 on 2021-05-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisorapp', '0005_bookedcall_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedcall',
            name='booking_time',
            field=models.DateTimeField(),
        ),
    ]
